"""
compiler.py — Prompt Compiler.

Takes a PanelSpec and produces a GenerationRequest — the fully assembled
payload for the Image Generation Backend.

Layer assembly order (fixed):
  [1] Style identity tokens
  [2] Shot type + mood tokens
  [3] Environment identity tokens
  [4] Character identity tokens
  [5] Scene prompt (LLM-generated by Scene Prompt Generator)
  [6] Negative / exclusion tokens (deduplicated)
  [7] Negative space directive (optional, deterministic from panel_seed)
  [8] Reference image descriptions (deterministic from selection metadata)

Layers [1–4] and [6–8] are deterministic. Layer [5] is an LLM call.

Per DESIGN.md §13.5: Returns structured data, no print() statements, no CLI logic.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


class ScenePromptError(Exception):
    """Raised when the Scene Prompt Generator LLM call fails."""
    pass


# -- Result types ------------------------------------------------------------

@dataclass(frozen=True)
class ReferenceSelection:
    """A selected reference image and its role assignment."""
    ref_id: str
    file: str
    role: str  # "character" or "environment"
    character_id: str | None = None
    environment_id: str | None = None
    purpose: str = ""
    priority: int = 999
    display_name: str = ""


@dataclass(frozen=True)
class GenerationRequest:
    """
    Fully assembled payload for the Image Generation Backend.

    The Backend Adapter receives this object and makes the API call.
    It needs no additional context — everything is embedded here.
    """
    panel_id: str
    model: str
    prompt: str
    size: str  # "1024x1024" | "1536x1024" | "1024x1536"
    quality: str
    thinking: str
    seed: int | None
    reference_images: list[dict[str, str]]
    panelspec_path: str
    compiler_version: str
    # Internal metadata (not sent to API, stored in Generation Record)
    _scene_prompt: str = ""
    _reference_selections: list[ReferenceSelection] = field(default_factory=list)
    _context_profile: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialise for the Provenance Store (includes internal metadata)."""
        return {
            "panel_id": self.panel_id,
            "model": self.model,
            "prompt": self.prompt,
            "size": self.size,
            "quality": self.quality,
            "thinking": self.thinking,
            "seed": self.seed,
            "reference_images": self.reference_images,
            "panelspec_path": self.panelspec_path,
            "compiler_version": self.compiler_version,
            "_scene_prompt": self._scene_prompt,
            "_reference_selections": [
                {
                    "ref_id": s.ref_id,
                    "file": s.file,
                    "role": s.role,
                    "character_id": s.character_id,
                    "environment_id": s.environment_id,
                    "purpose": s.purpose,
                    "priority": s.priority,
                    "display_name": s.display_name,
                }
                for s in self._reference_selections
            ],
            "_context_profile": self._context_profile,
        }


# -- Aspect ratio selector ---------------------------------------------------

# gpt-image-2 supported sizes and their aspect ratios
_SUPPORTED_SIZES = [
    ("1024x1024", 1.0),
    ("1536x1024", 1.5),    # landscape
    ("1024x1536", 0.667),  # portrait
]


def select_aspect_ratio(width_px: int, height_px: int) -> str:
    """
    Select the closest supported gpt-image-2 size for the given panel geometry.

    Returns one of "1024x1024", "1536x1024", "1024x1536".
    """
    target_ratio = width_px / height_px
    best = min(_SUPPORTED_SIZES, key=lambda s: abs(s[1] - target_ratio))
    return best[0]


# -- Reference image budget allocation ---------------------------------------

def allocate_reference_budget(
    characters: list[dict[str, Any]],
    environment: dict[str, Any] | None,
    budget: int,
) -> dict[str, list[dict[str, Any]]]:
    """
    Allocate the reference image budget across characters and environment.

    Strategy: proportional with guaranteed minimums.
    - Each character: guaranteed 1 slot.
    - Environment: guaranteed 1 slot if it has references.
    - Remaining slots distributed equally among characters, rounded down.
    - Leftover slots go to the primary character (first in array).
    - Underfill: unused slots are NOT redistributed.

    Returns a dict keyed by "character:{id}" or "environment:{id}",
    each containing the list of selected reference dicts.
    """
    char_count = len(characters)
    env_has_refs = environment is not None and len(environment.get("references", [])) > 0

    # Guaranteed minimums
    char_min = 1 if char_count > 0 else 0
    env_min = 1 if env_has_refs else 0
    guaranteed = char_count * char_min + env_min

    if guaranteed > budget:
        # Budget too small for full guarantees — give each character 1,
        # then environment if anything left.
        result: dict[str, list[dict[str, Any]]] = {}
        remaining = budget
        for char in characters:
            if remaining <= 0:
                break
            refs = sorted(char.get("references", []), key=lambda r: r.get("priority", 999))
            if refs:
                result[f"character:{char['character_id']}"] = [refs[0]]
                remaining -= 1
        if env_has_refs and remaining > 0:
            refs = sorted(environment["references"], key=lambda r: r.get("priority", 999))
            result[f"environment:{environment['environment_id']}"] = [refs[0]]
        return result

    remaining = budget - guaranteed

    # Distribute remaining slots equally among characters, rounded down
    extra_per_char = remaining // char_count if char_count > 0 else 0
    leftover = remaining - (extra_per_char * char_count)

    result = {}
    for i, char in enumerate(characters):
        allocation = char_min + extra_per_char
        # Primary character gets leftover
        if i == 0:
            allocation += leftover
        refs = sorted(char.get("references", []), key=lambda r: r.get("priority", 999))
        selected = refs[:allocation]
        if selected:
            result[f"character:{char['character_id']}"] = selected

    if env_has_refs:
        refs = sorted(environment["references"], key=lambda r: r.get("priority", 999))
        selected = refs[:env_min]
        if selected:
            result[f"environment:{environment['environment_id']}"] = selected

    return result


# -- Scene Prompt Generator --------------------------------------------------

class ScenePromptGenerator:
    """
    Sub-component of the Prompt Compiler.

    Translates the brief Chapter Plan panel description into a detailed,
    composable scene narrative suitable for image generation.

    Uses GPT-4o-mini (configurable via project.yaml).
    Stateles — each panel gets a fresh call with no memory.
    """

    def __init__(self, model: str, context_profile: str):
        self.model = model
        self.context_profile = context_profile

    def _build_system_prompt(self) -> str:
        return (
            "You are a scene prompt writer for a graphic novel production pipeline. "
            "Your job is to expand a brief panel description into a detailed, vivid scene "
            "description suitable for an AI image generator. "
            "Write in second person present tense (\"We see...\"). "
            "Focus on visual composition, lighting, character poses, and atmosphere. "
            "Do not describe text, speech bubbles, or lettering. "
            "Do not invent new characters or environments. "
            "Keep the description to 2-4 sentences. Be concrete and specific."
        )

    def _build_user_prompt(
        self,
        panel_spec: dict[str, Any],
        surrounding_descriptions: list[str] | None = None,
        user_feedback: str | None = None,
    ) -> str:
        parts: list[str] = []

        # Style tokens (layers 1-4 assembled)
        style = panel_spec.get("style", {})
        vs = style.get("visual_style", {})
        parts.append(f"Visual style: {vs.get('prompt_tokens', '')}")
        parts.append(f"Lighting: {style.get('lighting_defaults', '')}")

        # Shot type and mood
        parts.append(f"Shot type: {panel_spec.get('shot_type', '')}")
        parts.append(f"Mood: {panel_spec.get('mood', '')}")

        # Environment
        env = panel_spec.get("environment")
        if env:
            parts.append(f"Environment: {env.get('prompt_tokens', {}).get('identity', '')}")

        # Characters
        for char in panel_spec.get("characters", []):
            tokens = char.get("prompt_tokens", {})
            identity = tokens.get("identity", "")
            parts.append(f"Character {char.get('display_name', '')}: {identity}")

        # Continuity
        cont = panel_spec.get("continuity", {})
        if cont:
            parts.append(f"Time of day: {cont.get('time_of_day', '')}")
            parts.append(f"Location: {cont.get('location', '')}")

        # Continuity narrative (per-panel storyboard entry from the scene)
        continuity_narrative = panel_spec.get("continuity_narrative")
        if continuity_narrative:
            parts.append(f"\nContinuity narrative (visual storyboard for this panel): {continuity_narrative}")

        # Panel description (the core input)
        parts.append(f"\nPanel description: {panel_spec.get('description', '')}")

        # Surrounding panels for continuity
        if surrounding_descriptions:
            parts.append("\nSurrounding panels for context:")
            for desc in surrounding_descriptions:
                parts.append(f"  - {desc}")

        # User feedback (highest priority on regeneration)
        if user_feedback:
            parts.append(f"\nDIRECTOR'S NOTE (overrides all other instructions): {user_feedback}")

        return "\n".join(parts)

    def generate(
        self,
        panel_spec: dict[str, Any],
        surrounding_descriptions: list[str] | None = None,
        user_feedback: str | None = None,
        call_llm: Any = None,
    ) -> str:
        """
        Generate the scene prompt for a single panel.

        Args:
            panel_spec: The PanelSpec dict.
            surrounding_descriptions: Brief descriptions of adjacent panels.
            user_feedback: Optional human override instruction.
            call_llm: Callable (model, system_prompt, user_prompt) -> str.
                      If None, uses the real OpenAI API.

        Returns:
            The scene prompt string (layer [5]).
        """
        system_prompt = self._build_system_prompt()
        user_prompt = self._build_user_prompt(
            panel_spec, surrounding_descriptions, user_feedback
        )

        if call_llm is not None:
            return call_llm(self.model, system_prompt, user_prompt)

        return self._call_openai(system_prompt, user_prompt)

    def _call_openai(self, system_prompt: str, user_prompt: str) -> str:
        """Make the actual OpenAI API call."""
        from openai import OpenAI

        client = OpenAI()
        try:
            response = client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.7,
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            raise ScenePromptError(f"Scene prompt generation failed: {e}") from e


# -- Context management infrastructure (v1 placeholders) --------------------

class SceneContextStore:
    """
    Placeholder infrastructure for cross-panel context management.

    In v1, this is empty — the Scene Prompt Generator relies on the
    context_profile inputs alone. Future iterations can populate this
    with prior scene prompts, visual motifs, etc.
    """

    def __init__(self):
        self._store: dict[str, Any] = {}

    def curate_scene_context(self, panel_id: str) -> dict[str, Any]:
        """Select relevant entries for a given panel. No-op in v1."""
        return {}

    def update_scene_context(self, panel_id: str, scene_prompt: str, metadata: dict) -> None:
        """Store scene prompt result. No-op in v1."""
        pass


# -- Prompt Compiler ---------------------------------------------------------

class PromptCompiler:
    """
    Compiles a PanelSpec into a GenerationRequest.

    Assembles the prompt in the fixed six-layer order (plus reference
    descriptions as layer [8]). Handles reference image selection and
    budget allocation, negative space injection, and aspect ratio selection.
    """

    def __init__(self, config: Any):
        """
        Initialise the Compiler with project configuration.

        Args:
            config: ProjectConfig from pipeline.config.load_config.
        """
        self.config = config
        self.scene_prompt_generator = ScenePromptGenerator(
            model=config.scene_prompt.model,
            context_profile=config.scene_prompt.context_profile,
        )
        self.context_store = SceneContextStore()

    # -- Layer assembly (deterministic) --------------------------------------

    def _layer_style(self, panel_spec: dict[str, Any]) -> str:
        """Layer [1]: Style identity tokens."""
        style = panel_spec["style"]
        vs = style["visual_style"]
        parts = [vs.get("prompt_tokens", "").strip()]
        if vs.get("color_palette"):
            parts.append(vs["color_palette"].strip())
        if vs.get("line_weight"):
            parts.append(vs["line_weight"].strip())
        if vs.get("shading_approach"):
            parts.append(vs["shading_approach"].strip())
        return ". ".join(p for p in parts if p)

    def _layer_shot_mood(self, panel_spec: dict[str, Any]) -> str:
        """Layer [2]: Shot type + mood tokens."""
        shot = panel_spec.get("shot_type", "")
        mood = panel_spec.get("mood", "")
        parts = []
        if shot:
            parts.append(f"Shot: {shot}")
        if mood:
            parts.append(f"Mood: {mood}")
        return ", ".join(parts)

    def _layer_environment(self, panel_spec: dict[str, Any]) -> str:
        """Layer [3]: Environment identity tokens."""
        env = panel_spec.get("environment")
        if not env:
            return ""
        tokens = env.get("prompt_tokens", {})
        parts = [tokens.get("identity", "").strip()]
        return ". ".join(p for p in parts if p)

    def _layer_characters(self, panel_spec: dict[str, Any]) -> str:
        """Layer [4]: Character identity tokens (in array order)."""
        chars = panel_spec.get("characters", [])
        if not chars:
            return ""
        parts = []
        for char in chars:
            tokens = char.get("prompt_tokens", {})
            identity = tokens.get("identity", "").strip()
            costume = char.get("costume", {}).get("default", "").strip()
            if costume:
                parts.append(f"{identity}. Currently wearing: {costume}")
            else:
                parts.append(identity)
        return ". ".join(p for p in parts if p)

    def _layer_exclusions(self, panel_spec: dict[str, Any]) -> str:
        """Layer [6]: Negative/exclusion tokens (deduplicated)."""
        all_exclusions: list[str] = []

        # Style forbidden elements
        style = panel_spec.get("style", {})
        all_exclusions.extend(style.get("forbidden_elements", []))

        # Environment exclusions
        env = panel_spec.get("environment")
        if env:
            all_exclusions.extend(
                env.get("prompt_tokens", {}).get("exclusions", [])
            )

        # Character exclusions
        for char in panel_spec.get("characters", []):
            all_exclusions.extend(
                char.get("prompt_tokens", {}).get("exclusions", [])
            )

        # Deduplicate while preserving order
        seen: set[str] = set()
        unique: list[str] = []
        for ex in all_exclusions:
            if ex not in seen:
                seen.add(ex)
                unique.append(ex)

        return ", ".join(unique)

    def _layer_negative_space(self, panel_spec: dict[str, Any]) -> str:
        """Layer [7]: Negative space directive (deterministic from panel_seed)."""
        seed = panel_spec.get("panel_seed", "00")
        # Even hex byte → inject; odd → do not inject
        try:
            seed_value = int(seed, 16)
        except ValueError:
            return ""

        if seed_value % 2 == 0:
            return (
                "This composition should include relatively unused area of low detail where a speech bubble will eventually be added. "
                "Don't draw the bubble, just compose the image so an editor can add it later."
            )
        return ""

    def _layer_reference_descriptions(
        self,
        selections: dict[str, list[dict[str, Any]]],
    ) -> str:
        """Layer [8]: Reference image descriptions (deterministic)."""
        if not selections:
            return ""

        lines: list[str] = []
        index = 1
        for key, refs in selections.items():
            if key.startswith("character:"):
                char_id = key.split(":", 1)[1]
                for ref in refs:
                    purpose = ref.get("purpose", "reference")
                    display = ref.get("display_name", char_id)
                    # Convert purpose enum to readable text
                    purpose_text = purpose.replace("_", " ")
                    costume = ref.get("costume", "default")
                    lines.append(
                        f"Reference image {index}: {display}, "
                        f"{purpose_text} reference, {costume} costume."
                    )
                    index += 1
            elif key.startswith("environment:"):
                env_id = key.split(":", 1)[1]
                for ref in refs:
                    purpose = ref.get("purpose", "establishing_shot")
                    display = ref.get("display_name", env_id)
                    purpose_text = purpose.replace("_", " ")
                    lines.append(
                        f"Reference image {index}: {display}, "
                        f"{purpose_text} reference."
                    )
                    index += 1

        return "\n".join(lines)

    # -- Reference image selection -------------------------------------------

    def _select_references(
        self,
        panel_spec: dict[str, Any],
    ) -> tuple[dict[str, list[dict[str, Any]]], list[ReferenceSelection]]:
        """
        Select reference images within the budget and build selection records.

        Returns:
            (selections_dict, selection_records) where selections_dict maps
            "character:{id}"/"environment:{id}" → list of ref dicts (with
            display_name added), and selection_records is a list of
            ReferenceSelection objects.
        """
        budget = self.config.image_generation.reference_budget

        # Enrich references with display_name for the description layer
        characters = []
        for char in panel_spec.get("characters", []):
            enriched = dict(char)
            enriched_refs = []
            for ref in char.get("references", []):
                r = dict(ref)
                r["display_name"] = char.get("display_name", char["character_id"])
                enriched_refs.append(r)
            enriched["references"] = enriched_refs
            characters.append(enriched)

        environment = None
        env_data = panel_spec.get("environment")
        if env_data:
            environment = dict(env_data)
            env_refs = []
            for ref in env_data.get("references", []):
                r = dict(ref)
                r["display_name"] = env_data.get("display_name", env_data["environment_id"])
                env_refs.append(r)
            environment["references"] = env_refs

        selections = allocate_reference_budget(characters, environment, budget)

        # Build ReferenceSelection records
        selection_records: list[ReferenceSelection] = []
        for key, refs in selections.items():
            if key.startswith("character:"):
                char_id = key.split(":", 1)[1]
                for ref in refs:
                    selection_records.append(ReferenceSelection(
                        ref_id=ref["ref_id"],
                        file=ref["file"],
                        role="character",
                        character_id=char_id,
                        purpose=ref.get("purpose", ""),
                        priority=ref.get("priority", 999),
                        display_name=ref.get("display_name", char_id),
                    ))
            elif key.startswith("environment:"):
                env_id = key.split(":", 1)[1]
                for ref in refs:
                    selection_records.append(ReferenceSelection(
                        ref_id=ref["ref_id"],
                        file=ref["file"],
                        role="environment",
                        environment_id=env_id,
                        purpose=ref.get("purpose", ""),
                        priority=ref.get("priority", 999),
                        display_name=ref.get("display_name", env_id),
                    ))

        return selections, selection_records

    # -- Full compilation -----------------------------------------------------

    def compile(
        self,
        panel_spec: dict[str, Any],
        surrounding_descriptions: list[str] | None = None,
        user_feedback: str | None = None,
        call_llm: Any = None,
    ) -> GenerationRequest:
        """
        Compile a PanelSpec into a GenerationRequest.

        Args:
            panel_spec: The PanelSpec dict (loaded from .panelspec.json).
            surrounding_descriptions: Brief descriptions of adjacent panels
                                      for continuity context.
            user_feedback: Optional human override for regeneration.
            call_llm: Optional callable to mock the Scene Prompt Generator.
                      Signature: (model, system_prompt, user_prompt) -> str.

        Returns:
            GenerationRequest ready for the Image Generation Backend.
        """
        panel_id = panel_spec["panel_id"]

        # -- Reference image selection (before prompt assembly for layer [8]) --
        selections, selection_records = self._select_references(panel_spec)

        # -- Layer [5]: Scene prompt (LLM call) --
        scene_prompt = self.scene_prompt_generator.generate(
            panel_spec=panel_spec,
            surrounding_descriptions=surrounding_descriptions,
            user_feedback=user_feedback,
            call_llm=call_llm,
        )

        # Update context store (no-op in v1)
        self.context_store.update_scene_context(panel_id, scene_prompt, {})

        # -- Assemble the full prompt string --
        layers: list[str] = []

        # [1] Style
        layer1 = self._layer_style(panel_spec)
        if layer1:
            layers.append(layer1)

        # [2] Shot + Mood
        layer2 = self._layer_shot_mood(panel_spec)
        if layer2:
            layers.append(layer2)

        # [3] Environment
        layer3 = self._layer_environment(panel_spec)
        if layer3:
            layers.append(layer3)

        # [4] Characters
        layer4 = self._layer_characters(panel_spec)
        if layer4:
            layers.append(layer4)

        # [5] Scene prompt
        layers.append(scene_prompt)

        # [6] Exclusions
        layer6 = self._layer_exclusions(panel_spec)
        if layer6:
            layers.append(f"Exclude: {layer6}")

        # [7] Negative space
        layer7 = self._layer_negative_space(panel_spec)
        if layer7:
            layers.append(layer7)

        # [8] Reference image descriptions
        layer8 = self._layer_reference_descriptions(selections)
        if layer8:
            layers.append(layer8)

        prompt = "\n\n".join(layers)

        # -- Aspect ratio selection --
        geo = panel_spec["panel_geometry"]
        size = select_aspect_ratio(geo["width_px"], geo["height_px"])

        # -- Build reference_images list for the Backend --
        reference_images: list[dict[str, str]] = []
        for sel in selection_records:
            # Resolve the file path relative to the project root
            if sel.role == "character":
                file_path = f"characters/{sel.file}"
            else:
                file_path = f"environments/{sel.file}"
            reference_images.append({
                "ref_id": sel.ref_id,
                "file": file_path,
                "role": sel.role,
            })

        # -- Build the GenerationRequest --
        ig = self.config.image_generation

        return GenerationRequest(
            panel_id=panel_id,
            model=ig.model,
            prompt=prompt,
            size=size,
            quality=ig.quality,
            thinking=ig.thinking,
            seed=ig.seed,
            reference_images=reference_images,
            panelspec_path=f"output/{panel_id}.panelspec.json",
            compiler_version=self.config.compiler_version,
            _scene_prompt=scene_prompt,
            _reference_selections=selection_records,
            _context_profile=self.config.scene_prompt.context_profile,
        )
